/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BudgetItem: typeof import('./src/components/budget/BudgetItem.vue')['default']
    BudgetSummary: typeof import('./src/components/budget/BudgetSummary.vue')['default']
    CategoryTable: typeof import('./src/components/category/CategoryTable.vue')['default']
    DailyExpense: typeof import('./src/components/chart/DailyExpense.vue')['default']
    EditBudgetDialog: typeof import('./src/components/budget/EditBudgetDialog.vue')['default']
    EditCategoryDialog: typeof import('./src/components/category/EditCategoryDialog.vue')['default']
    EditRecordDialog: typeof import('./src/components/record/EditRecordDialog.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    IconEpCirclePlus: typeof import('~icons/ep/circle-plus')['default']
    IconEpDelete: typeof import('~icons/ep/delete')['default']
    IconEpEdit: typeof import('~icons/ep/edit')['default']
    IconEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IconEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    IconLucideTimerReset: typeof import('~icons/lucide/timer-reset')['default']
    IconTablerDropletDollar: typeof import('~icons/tabler/droplet-dollar')['default']
    RecordTableV1: typeof import('./src/components/record/RecordTableV1.vue')['default']
    RecordTableV2: typeof import('./src/components/record/RecordTableV2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
